AllCops:
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'spec/*_helper.rb'
    - 'test/*_helper.rb'
    - 'Vagrantfile'
    - 'lib/tasks/cucumber.rake'
Metrics/MethodLength:
  Max: 15
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
