version: "3.3"

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./db_docker:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres_db



  web:
    build:
      context: .
      dockerfile: docker-web/Dockerfile
    volumes:
      - .:/home/site/School-Planner
    ports:
      - "3000:3000"
    command: >
      bash -c "rake db:create
      && rake db:migrate
      && rake db:seed
      && rails server -b 0.0.0.0"
